export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const INPUT_TEXT = 'INPUT_TEXT'

export const COMMENT_CREATE = 'COMMENT_CREATE'
export const COMMENT_UPDATE = 'COMMENT_UPDATE'
export const COMMENT_DELETE = 'COMMENT_DELETE'

export const COMMENTS_LOAD = 'COMMENTS_LOAD'
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON'
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF'